## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import scipy as scipy

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
array = np.random.randint(low=1, high=10, size=100)
array[(3 <= array) & (array <= 8)] = -array[(3 <= array) & (array <= 8)]

**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
array = np.random.randint(low=1, high=10, size=100)
prev_max, prev_max_pos = array.max(), np.argmax(array)
array[prev_max_pos] = 0
cur_max, cur_max_pos = array.max(), np.argmax(array)
print(f"Prev max: {prev_max}, prev pos: {prev_max_pos}")
print(f"Current max: {cur_max}, cur pos: {cur_max_pos}")

Prev max: 9, prev pos: 2
Current max: 9, cur pos: 6


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
x = np.arange(9.0).reshape((3, 3))
y = np.arange(9.0, 18.0).reshape((3, 3,))
np.multiply(x, y)

array([[  0.,  10.,  22.],
       [ 36.,  52.,  70.],
       [ 90., 112., 136.]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.random.randint(low=1, high=10, size=(8, 3))
B = np.random.randint(low=1, high=10, size=(2, 2))

print("A = \n", A, end='\n\n')
print("B = \n", B, end='\n\n')

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(axis=1))[0]
print("Rows: ", rows)
print("In A: ", A[rows])

A = 
 [[8 2 3]
 [8 5 5]
 [6 3 3]
 [9 9 4]
 [1 3 4]
 [2 3 6]
 [3 3 4]
 [3 9 5]]

B = 
 [[8 3]
 [1 9]]

Rows:  [4 7]
In A:  [[1 3 4]
 [3 9 5]]


 **5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
matrix = np.random.randint(low=1, high=10, size=(10, 3))
print(matrix)

mask = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
new_matrix = matrix[~mask]
print(new_matrix)

[[9 8 8]
 [4 8 3]
 [5 8 9]
 [8 7 7]
 [3 3 6]
 [7 1 4]
 [5 3 2]
 [8 5 9]
 [8 9 8]
 [5 2 5]]
[[9 8 8]
 [4 8 3]
 [5 8 9]
 [8 7 7]
 [3 3 6]
 [7 1 4]
 [5 3 2]
 [8 5 9]
 [8 9 8]
 [5 2 5]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
array = np.random.randint(low=1, high=10, size=(100, 1))
new_array = np.unique(array, axis=0)
_, counts = np.unique(new_array, axis=0, return_counts=True)
assert len(new_array[counts > 1]) == 0
print(new_array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [44]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

def numpy_solve():
    return X.diagonal()[X.diagonal() > 0].prod()

result = %timeit -o numpy_solve()
print("Result =", numpy_solve())

4.41 µs ± 479 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Result =  3


In [45]:
from functools import reduce

X_pure = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

def pure_python_solve():
    return reduce((lambda i, j: i * j), [X_pure[i][i] for i in range(min(len(X_pure), len(X_pure[0]))) if X_pure[i][i] > 0])

%timeit pure_python_solve()
print("Result =", pure_python_solve())

928 ns ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
Result =  3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [51]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

def numpy_solve():
    return np.array_equiv(np.sort(x,axis=0), np.sort(y,axis=0))

%timeit numpy_solve()
print("Result =", numpy_solve())

8.48 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Result =  True


In [52]:
x_pure = [1, 2, 2, 4]
y_pure = [4, 2, 1, 2]

def pure_python_solve():
    x = sorted(x_pure)
    y = sorted(y_pure)
    return x == y

%timeit pure_python_solve()
print("Result =", pure_python_solve())

362 ns ± 3.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
Result = True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [66]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def numpy_solve():
    return x[1:][(x == 0)[:-1]].max()

%timeit numpy_solve()
print("Result =", numpy_solve())

4.45 µs ± 66.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Result = 5


In [67]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def pure_python_solve():
    return max(x[i] for i in range(1, len(x)) if not x[i-1])

%timeit pure_python_solve()
print("Result =", pure_python_solve())

873 ns ± 29 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
Result = 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [81]:
x = np.random.randint(low=1, high=11, size=1000)

def numpy_solve():
    return np.unique(x, return_counts=True)

%timeit numpy_solve()
print("Result =", numpy_solve())

32.8 µs ± 4.99 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Result = (array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 97,  99, 109, 123, 104,  99,  90,  97,  97,  85]))


In [82]:
from random import randint, random
from collections import defaultdict

x = [randint(a=1, b=10) for i in range(1000)]

def pure_python_solve():
    d = defaultdict(lambda: 0)
    for i in x:
        d[i] += 1
    return d.keys(), d.values()

%timeit pure_python_solve()
print("Result =", pure_python_solve())

67.1 µs ± 3.52 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
Result = (dict_keys([8, 7, 5, 2, 6, 10, 4, 9, 3, 1]), dict_values([92, 114, 102, 121, 104, 91, 85, 98, 102, 91]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [102]:
import scipy

x = np.random.rand(100, 100)
y = np.random.rand(100, 100)

def scipy_solve():
    return scipy.spatial.distance.cdist(x, y)

%timeit scipy_solve()

392 µs ± 59.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [103]:
import math

x = [[random() for j in range(100)] for i in range(100)]
y = [[random() for j in range(100)] for i in range(100)]

def pure_python_solve():
    matrix = []
    for i in x:
        matrix.append([])
        for j in y:
            matrix[-1].append(math.sqrt(sum([(a - b) ** 2 for a, b in zip(i, j)])))
    return matrix

%timeit pure_python_solve()

117 ms ± 900 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [112]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [113]:
average_calories = calorie_stats.mean()
print(f"Average calories: {average_calories}, upon our product: {average_calories - 60.}")

Average calories: 106.88311688311688, upon our product: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [114]:
calorie_stats_sorted = calorie_stats
calorie_stats_sorted.sort()
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [116]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [138]:
nth_percentile = 100
value = np.percentile(calorie_stats, nth_percentile)
while value > 60:
    nth_percentile -= 1
    value = np.percentile(calorie_stats, nth_percentile)
nth_percentile += 1
print(f"{nth_percentile}%")

4%


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [143]:
calorie_stats[calorie_stats > 60].shape[0]/calorie_stats.shape[0] * 100

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [147]:
calorie_std = np.std(calorie_stats)
print(f"Mean: {median_calories} +- {calorie_std}")

Mean: 110.0 +- 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Полученные данные можно использовать при разработке или улучшении формулы производимого продукта. Можно заранее рассчитать насколько продукт лучше своих конкурентов, качество этого продукта, при доп имнформации по продажам конкурентов, думаю, можно сделать предположение о доходе.
Найденные данные также можно успешно использовать в маркетинговой продукции компании, например можно указать на упаковке батончиков процент конкурентов, которым продукт уступает по калоражу.